### ISSUE TITLE
地形データ残件

### ISSUE THREAD

**Issue by qoopen0815** [Field-Robotics-Japan/vtc_world_unity#4]
https://github.com/Field-Robotics-Japan/vtc_world_unity/pull/3 より

【残件】
- [x] 地形以外のobject位置の修正
- [x] 市役所前の地形をもう少し滑らかにする
- [x] 市役所側面入口側のテクスチャを修正する

**Comment by RyodoTanaka** [comment]
object位置の修正について
現状，Realistic Tree のAssetがうまく読み込めてないっぽくて，いくつか木が抜け落ちてます．
木のモデルについては自作し直しで置き直した方が良さそうですね．
市役所について，Blender内ではすでにきれいなものに置き換わっていたと思います．
BlenderのCity Hallを更新してそのままimportできるようになると良いですね！

**Comment by qoopen0815** [comment]
残件完了したのでクローズします。
