### ISSUE TITLE
vtc_world_unityの利用

### ISSUE THREAD

**Issue by ssilph** [Field-Robotics-Japan/vtc_world_unity#8]
個人参加チーム00_initチームのxieです.

vtc_world_unityのファイルはrosなしの単体で利用可能でしょうか？
現在git cloneし，unity2019で開いたファイルですが，
床の情報とホール全体の情報が消えて表示されます．

git lfs pullを行っても同じ状態です．

![Screenshot from 2020-08-05 15-25-54](https://user-images.githubusercontent.com/17755974/89379026-ff025880-d72f-11ea-8cbb-0941a2fc59da.png)

何か対処法がご存知の方，教えてください．

**Comment by RyodoTanaka** [comment]
@ssilph 
Xieさん，早速のご連絡ありがとうございます．
下記お答えします．

> vtc_world_unityのファイルはrosなしの単体で利用可能でしょうか？

はい．ROSを使うこと無く利用可能です．

> 現在git cloneし，unity2019で開いたファイルですが，
> 床の情報とホール全体の情報が消えて表示されます．
> git lfs pullを行っても同じ状態です．

本問題について，つい昨日大幅な修正Commitを行いました．
お手数をおかけし申し訳ありませんが，

1. ローカルの`vtc_world_unity`を一度削除
```bash
$ rm -rf vtc_world_unity
```
2. 再度`master`ブランチを`git clone`
```bash
$ git clone -b master https://github.com/Field-Robotics-Japan/vtc_world_unity.git
```
上記を試していただけると嬉しいです．
よろしくお願いします．

**Comment by ssilph** [comment]
@RyodoTanaka 

Tanakaさん，早速のご返事ありがとうございます．
何度もすみません．

上の画像はすでに本日で再度git cloneしたものであり，
先程ご返事を頂いた後もコメントに従い，
2台のPCでそれぞれ試しましたが，
同じ問題が再現できました．

低木などはgit lfs pullのコマンドによって表示されましたが，
床とホールは相変わらず表示されませんでした．

作業環境：
　ubuntu 18.04
　unity hub 2.3.2
　unity version 2019.3.10f1

自分も調べてみますが，何か対処法がわかりましたら，
教えていただきたいです．

よろしくお願いいたします．

**Comment by qoopen0815** [comment]
@ssilph 

Xieさん、報告ありがとうございます。

上記に添付していただいた画像をみると、
「vtc_environment_assy」が表示されていないようにみえます。
このモデルに対してUnity側からなにかエラーなど出てないでしょうか？
確認お願いします。

**Comment by RyodoTanaka** [comment]
@ssilph 
Xie さん
お返事ありがとうございます．
また，すぐに解決策が出せずすみません．

当方でも数台のPCにて検証しましたが，問題が再現できず，解決策がわかっていないです．
見ている限りではBlenderで作成している `vtc_enviroment_assy`がうまく読み込めていないですね...
一応念の為，最新コミット(42bb8b46322b6c433d4b68c849def5b0626f1aec)になっているかの確認をよろしくお願いします．

**Comment by RyodoTanaka** [comment]
@calm0815 
もしかして Blender が入っていないとうまくインポートできない
みたいな罠って無いですかね？
Blender -> Unity の変換がうまく行ってないだけなので，その周りで思いつくことあれば言っていただけると嬉しいです．

**Comment by qoopen0815** [comment]
@RyodoTanaka 
@ssilph 

> もしかして Blender が入っていないとうまくインポートできない
みたいな罠って無いですかね？

下記によればその可能性は十分ありそうです。
https://docs.unity3d.com/560/Documentation/Manual/HOWTO-ImportObjectBlender.html

Xieさん
Blender(v2.6以上)をインストール後、Unityを再度ロードしてみてください。
よろしくお願いします。

**Comment by RyodoTanaka** [comment]
@calm0815 
おお！調査ありがとうございます．
 嫌な予感が当たってしまいましたね...:scream:
Blender>=2.6が入ってないと動かないというのは，検証後にREADMEに書く必要がありますね．
もしくは，Prefab展開して依存が無いようにするか...

@ssilph 
お手数ですが， @calm0815 さんの言うとおり，Blender >=2.6 をインストールして，再度Unityをロード（`git clone`の必要は無し）してみてください．

**Comment by ssilph** [comment]
@RyodoTanaka
@calm0815

いろいろ調べていただきありがとうございます．

blenderは最初にインストールしたPCの方に，すでに入ってます．
以前強化学習のモデルを作るとき用いたことがあります．

もう片方のPCではunityのエラーで気づき，
sudo apt install blenderで2.79を入れました．
問題は相変わらず解決できていません．

可能性があるwarning:
rmしてもう一度git cloneで気づきましたが，初回ロードする時のみ出るメッセージがこのようになります．

![Screenshot from 2020-08-05 18-22-15](https://user-images.githubusercontent.com/17755974/89395778-b7d49180-d748-11ea-9064-0b38223c1434.png)

この中で注目していただきたいのはwarningのこの3行
A polygon of OfficeRoom is self-intersecting and has been discarded.
A polygon of Monitor is self-intersecting and has been discarded.
A polygon of Monitor is self-intersecting and has been discarded.

polygonが自己交差しているため削除したと書かれています．
double facesという問題らしくて，解決策としてこの動画があります．
https://www.youtube.com/watch?v=s2Df3C3_IYE

しかし，制作環境では問題なく表示されていて，この問題ではない可能性もあります．
blender本体以外のpolygon関連のライブラリなどを追加していないでしょうか？

私の方で調べた結果は現在ここまでです．何かわかりましたら，また報告いたします．

**Comment by RyodoTanaka** [comment]
@ssilph 
お返事が遅くなり失礼しました．

Blender>=2.6 はすでにインストールされており，これが原因ではないということ，承知しました．
貼って頂いたConsole 画面に， Warning と Error が出ている点について，こちらでの起動時のConsole画面は以下のとおりです．
![Screenshot_20200806_032319](https://user-images.githubusercontent.com/8377208/89449638-56d2ab00-d794-11ea-9d8e-209d8ebd7512.png)

ご提示頂いたものと同じError&Warning + 別の Warning が出ています（が，問題なく動作しています） :sweat_smile: 

ひとまず，ご質問頂いているPolygonに関するパッケージとして

- [Polybrush](https://unity3d.com/unity/features/worldbuilding/polybrush)

を利用しています．
導入方法は
`Window>PackageManager`でパッケージマネージャーを開き`PolyBrush`をインポート
です．
ちなみに導入されている Package 一覧は下図のとおりです．
![Screenshot_20200806_032233](https://user-images.githubusercontent.com/8377208/89449893-b2049d80-d794-11ea-879e-4b14ef98bdd7.png)


Blenderについてですが，当方で利用しているバージョンは2.83.3 です．
BlenderファイルをUnityにインポートするには Blender>=2.6であれば良いはずなのですが，もしかするとBlender2.8以上にしか無い機能等のせいで失敗しているかもしれません．（あくまであてずっぽうな推測です...）
他に決定的な原因と対策が思いつかない場合は Blenderのバージョンを2.8以上に上げていただいて，もう一度試していただけると幸いです．
なお，Blender>=2.8のインストール方法は
```bash
$ sudo apt remove blender
$ sudo add-apt-repository ppa:thomas-schiex/blender
$ sudo apt update
$ sudo apt install blender
```
です．

以上，決定的な解決策が示せず申し訳ありませんが，よろしくお願いします．

**Comment by ssilph** [comment]
@RyodoTanaka 
もう一つの原因の可能性はPointCloudViewerに関連するかもしれません．

私の環境ではblenderがインストールされていますが，
PointCloudViewerのadd-onが追加されていません．
しかし，PointCloudViewerをインストールの最中に，
numpyのmultilayerがないとのエラーメッセージが出て，
現在解決中です．

もしblenderのライブラリとunityの描画に関連していれば，
blenderで表示できなかったら，unityの表示も同じくできない可能性があります．

**Comment by qoopen0815** [comment]
@ssilph 

Xieさん、引き続きの検証ありがとうございます。
最初に貼っていただいた画像で気になったことがひとつあります。

Scene画面では「vtc_environment_assy」のアセットが表示されてませんが、
Hieralchy画面のvtc_environment_assyは正常にロードされているように見えます。

そこで初歩的な疑問なんですが、
何らかの操作でこれが非表示になっている可能性はないでしょうか。

また、Blenderのファイルは、Unityで読み込むとPrefabとして表示されます。
そこで、Hieralchy画面上のvtc_environment_assyを消していただいて、
Project画面から再度配置してみてもらえないでしょうか。
座標はすべて０でOKです。


- 非表示の可能性
- 再配置したら解決するか

この2点を検証お願いします。

**Comment by ssilph** [comment]
@RyodoTanaka 
@calm0815 

先程こちらの打ち合わせがありまして，
返事遅くてすみません．

いい情報を伝えます！
blender2.83+bpyをインストールしたら，描画できました！

![Screenshot from 2020-08-06 14-18-35](https://user-images.githubusercontent.com/17755974/89494035-51a34980-d7f0-11ea-87a5-a3af6342749e.png)

推測ですが，keyとなるのはbpyライブラリです．
いくつかの環境で試した結果は以下通りです（X：描画しない，O：描画した，？：未確認）：
X blender2.79 + PointCloudViewer(version=2.7x)
X blender2.79 + PointCloudViewer(version=2.7x) + bpy(version=2.7x)
X blender2.83 + PointCloudViewer(version=2.8x)
O blender2.83 + PointCloudViewer(version=2.8x) + bpy(version=2.8x)
？ blender2.83 + bpy(version=2.8x)

blender2.83 + PointCloudViewer(version=2.8x) + bpy(version=2.8x)の環境でも，
numpyのmultilayerがないとのエラーは修正できていませんが，
unityの描画はできますので放置しています．

以上の結果を踏まえて，環境実装の手順は以下通りです．

**１．unity(2019.3.10f1)のinstall**
**２．blender2.83のinstall**
`
$ sudo apt remove blender
`
`
$ sudo add-apt-repository ppa:thomas-schiex/blender
`
`
$ sudo apt update
`
`
$ sudo apt install blender
`
**３．PointCloudViewer(version=2.8x) + bpy(version=2.8x)のインストール**
https://github.com/uhlik/bpy#point-cloud-visualizer-for-blender-280からzipをdownload
zipファイルでinstall:
blender->Edit(画面左上)->Preferences->Add-ons(左側)->install(右上)->zipファイル選択->install Add-on
zipを展開し，space_view3d_point_cloud_visualizer.pyも同じ手順でinstall:
blender->Edit(画面左上)->Preferences->Add-ons(左側)->install(右上)->space_view3d_point_cloud_visualizer.pyファイル選択->install Add-on

**4.unityでvtc_world_unityを開く**

できなかったら以下を試す．
`
$ git clean -fdx
`
`
$ git lfs pull
`

すごくリアリティのあるシミュレーション環境作成ありがとうございます．
また，何か手伝えることがあれば，ぜひお呼びください．
よろしくお願いいたします．

**Comment by RyodoTanaka** [comment]
@ssilph 
おおおおお！
動いてよかったです！
また，検証をいただきありがとうございます！！

頂いた環境構築法をそのまま READMEに記載させていただきます．

@calm0815 
`vtc_world_unity`で配布するデータの中では，不必要な PointCloud Data等は無くした方が良いかもですね．
ひとまず現状は READMEに記載ということで回避しますが，おそらくコレは `vtc_unity`の方でも起きてしまうので，早急に考えましょう．
今パッと思いつくのは
- `vtc_world_unity` `vtc_unity`には必要最低限のデータのみを配置（Prefab展開したものとしても良いかも）
- `vtc_world_blender` の方で，PointCloudデータ等，モデリングに必要なデータすべてを管理
という方法です．

READMEに記載が完了次第，こちらのIssueは閉じさせていただきます．

@ssilph 
Xie さん，ありがとうございました！！
環境データの更新などまだまだ開発は続くので，よろしくお願いします！

**Comment by qoopen0815** [comment]
@RyodoTanaka 
現状、Blenderファイルの読み込み作業を利用者の環境で行う仕様になっていることが
今回のトラブルにつながったと推測します。
よって、これからの開発では、
Blenderからの読み込み後、Prefabはすぐに展開してしまうのがいいと思います。

@ssilph 
Xieさん、バグの報告や調査ありがとうございました。
今後バグや実装の要望などありましたら、またよろしくお願いします。

**Comment by RyodoTanaka** [comment]
READMEのアップデートが完了しました．

@calm0815 
Prefab展開する方法で行きましょう．
コレに関して別Issueを建てました．-> #9 
どうやって行うか（blenderファイルの管理方法など）はそちらで議論しましょう．
よろしくお願いします．
