### ISSUE TITLE
Blender ファイルの Prefab 展開について

### ISSUE THREAD

**Issue by RyodoTanaka** [Field-Robotics-Japan/vtc_world_unity#9]
#8 で提起されている問題についてです．
blenderファイルを直接インポートし，現在はPrefab展開をせずに利用しています．
故に，Prefab展開を行う方針で行きますが，その際のBlenderファイル等の管理方法を議論しましょう．

**Comment by qoopen0815** [comment]
現在、vtc_world_unityとvtc_world_blenderの両方にBlenderファイルが存在しており、
vtc_world_blenderのほうをメインに編集を進め、進捗がたまり次第vtc_world_unity内のBlenderファイルを更新する
という運用方法であると認識してます。

Prefab展開をするのであれば、vtc_world_unity内にはBlenderファイルを置く必要がないように思いますがいかがでしょうか

**Comment by RyodoTanaka** [comment]
@calm0815 
おっしゃるとおりの方法で良いと思います．
一応今の形態（Blenderファイルがダブってるような）になっている経緯として

1. `vtc_world_blender`にBlenderをアップロード -> `vtc_world_unity` をアップデートで開発をしていた．
2. 当時は blender で作成ファイルを fbx に変換 -> unity でテクスチャ付 をやっていたが，管理が面倒だと考えていた．
3. Unity で直接 blender ファイルを読み取れることを知る -> `vtc_world_unity` 内部にblender ファイルを配置して管理するようになる．
4. 今回の問題が判明．再び初期の管理方法に戻そうかな？ <- 今ここ

という感じです．
よろしくお願いします！

**Comment by qoopen0815** [comment]
@RyodoTanaka 
経緯について承知しました。

現在vtc_world_unity内にあるBlender製PrefabはBlenderとリンクしているので、
展開→再Prefab化
を行うことでBlenderとのリンクを切りましょう。

Project/Assets/vtc_world_unity/Blender/Materials
に関しては、
①このまま残す
②Project/Assets/vtc_world_unity/Materialsに移動する
の2択が考えられますがどうしましょうか
Textureフォルダについても同様です。

**Comment by RyodoTanaka** [comment]
@calm0815 
返事遅くなってすみません．

> Project/Assets/vtc_world_unity/Blender/Materials
> に関しては、
> ①このまま残す
> ②Project/Assets/vtc_world_unity/Materialsに移動する
> の2択が考えられますがどうしましょうか
> Textureフォルダについても同様です。

わかりやすさから，後者にしたほうが良いと思います．
前者のままだと，`vtc_world_unity`だけを見てる人からすればなぜ`Blender`と名前がついてるかわからず，混乱を生むかと考えました．
よろしくお願いします．

**Comment by RyodoTanaka** [comment]
@calm0815 
本件，急がんといかんですね...
Prefab展開でリリースするために必要なこととして
- [ ] CityHallの草を簡易モデルに変える
- [ ] CityHall内の照明をつける
- [ ] CityHallの傾斜に対応した地形に変更
- [ ] CityHallに自動ドアをつける
- [ ] CityHallのテクスチャを適当に設定する

というものがあるかと思ってます．
他に必要なものや逆に不要なものがあれば教えてくださいm(_ _)m

**Comment by qoopen0815** [comment]
@RyodoTanaka 
issue対応ありがとうございます。

Prefab展開について思うことを以下にまとめます。

> CityHallの草を簡易モデルに変える

![image](https://user-images.githubusercontent.com/26988372/90356962-48399d00-e08c-11ea-8122-fddbb196bfe0.png)
これは「円柱でできた柵(collision : true)」の上に「雑草類のテクスチャ(collision : false)」を重ねる構成でいいと思います。点群の中に雑草類の形状は必要ないというのが個人的な見解です。

> CityHall内の照明をつける

これは現地の調査が必要ですね。
早いとこ調査を済ませないと市役所内部の編集作業は進めずらい印象です。
19~21の3日間、仕事の都合で栃木にいるのですが、最終日の午後から時間をとることができます。
横浜への帰路の途中に調査をするのもアリなので、検討の程よろしくお願いします。

> CityHallの傾斜に対応した地形に変更

補足しておきますと、
市役所の地面は屋内と屋外とで分割する予定です。
屋内の形状を調整した後に、屋外の地面を合わせこむというやり方を考えてます。

> CityHallに自動ドアをつける

市役所が形にならないとつけたくてもつけられないというのが現在の認識です。
スクリプトは完成してるので条件がそろえばすぐにでもつけられます。

> CityHallのテクスチャを適当に設定する

現地から採取したいですね。なんでもいいんですけども。笑

**Comment by qoopen0815** [comment]
肝心なことを伝え忘れてました。

Prefab展開について解決できてない問題がもう一つあります。
「UnityでBlender製Prefabを"unpacked completely"した後に、元となるBlederファイルを削除すると、unpackしたモデルがSceneから消える」
という事象です。
これについての調査が一番先だと思います。
よろしくお願いします。

**Comment by RyodoTanaka** [comment]
@calm0815 

> 「UnityでBlender製Prefabを"unpacked completely"した後に、元となるBlederファイルを削除すると、unpackしたモデルがSceneから消える」
> という事象です。
> これについての調査が一番先だと思います。

これが一番解決しないといけない問題ですね...
一番イヤな予感として，Blender無しで展開はできなくて（Blenderファイルと紐付けられてる），結局FBXやColladaにして出力しないといけなかったパターンがある可能性が...

いずれにせよ，この問題はなる早で結論出しましょう．
その他のアイデアやコメントについては承知しました．
ひとまず上記問題にのみ集中しましょう...！

**Comment by RyodoTanaka** [comment]
@calm0815 
上記問題，結局，利用者にBlenderのインストールをお願いすることになりそうですね．
READMEにもその手順は書いておいたので，Prefab展開するかどうかにかかわらず，Blenderありきでの開発
という方向にしようと思います．
同意ということであれば，本PRは閉じます．
よろしくお願いします！

**Comment by qoopen0815** [comment]
@RyodoTanaka 利用者にアドオンのインストールをお願いする方針でいいと思います。今後解決できそうであれば改善することにして、今はそっとしておくのがいいと思います。

**Comment by RyodoTanaka** [comment]
ではその方針で行きましょう！
閉じます！
